### ISSUE TITLE
fix/store-register-react

### ISSUE THREAD

**Issue by dazzlingtea** [SpringProject24/FoodieTree_frontend#25]
## Desc
상품 등록 미리보기 이미지 scss 수정

## Detail
상품 등록 폼에서 이미지를 업로드 시 미리보기 이미지 위치를 벗어나는 현상

## Todo
- [ ] 병합 후 발생한 scss문제 수정
- [ ] 컬러 수정
- [ ] 아이콘으로 검증메세지 보완
- [ ] 반응형 모바일 400px로 변경
